---
# tasks file for config_wordpress
- name: Site config
  template:
    src: "wordpress.j2"
    dest: "/etc/nginx/sites-available/wordpress"
  notify: Reload Nginx

- name: Site enable
  file:
    src: "/etc/nginx/sites-available/wordpress"
    dest: "/etc/nginx/sites-enabled/wordpress"
    state: link
  tags: [ wordpress ]
  notify: Reload Nginx

- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/html/wordpress/wp-config.php"
  tags: [ wordpress ]
  notify: Reload Nginx
